### ISSUE TITLE
how get entity log in controller?

### ISSUE THREAD

**Issue by nestor91sanchez** [madmis/ActivityLogBundle#2]

**Comment by madmis** [comment]
You should use [LogEntryRepository](https://github.com/madmis/ActivityLogBundle/blob/master/Repository/LogEntryRepository.php)

```
$em = $this->getDoctrine()->getManager();
$entries =  $em
            ->getRepository('AppBundle:LogEntry')
            ->getLogEntriesQueryBuilder($entity)
           ->getQuery()
          ->getResult();
$entries = $this
            ->get('activity_log.formatter')
            ->format($entries);
```

For `$entity` should be configured [Entity formatter](https://github.com/madmis/ActivityLogBundle#using-formatter-to-data-view)

I will add this description to documentation.
