### ISSUE TITLE
Adding extra services into custom formatters is not possible

### ISSUE THREAD

**Issue by TwanVermeulen** [madmis/ActivityLogBundle#3]
I have a custom formatter that requires some other services, like a translator and phonenumber formatter service

At this moment this is not possible, as all custom formatters only get initialised with an entitymanager.

I think it's better to load custom formatters via service tags. 

By using service tags, you can add your own dependencies to each of your custom formatters

**Comment by madmis** [comment]
@TwanVermeulen, pull request approved. Thank you.
